;; MIT License Copyright (c) 2008 Burke Libbey <burke@burkleibbey.org>

(defun color-theme-ir-black ()
  "Ported from a similar vim theme by Burke Libbey"
  (interactive)
  (color-theme-install
	'(color-theme-ir-black
	  ((background-color . "black")
		(background-mode . dark)
		(border-color . "black")
		(cursor-color . "#A7A7A7")
		(foreground-color . "#F8F8F8")
		(mouse-color . "sienna1"))
	  (default ((t (:background "black" :foreground "white"))))
	  (blue ((t (:foreground "blue"))))
	  (bold ((t (:bold t))))
	  (bold-italic ((t (:bold t))))
	  (border-glyph ((t (nil))))
	  (buffers-tab ((t (:background "black" :foreground "white"))))
	  (font-lock-builtin-face ((t (:foreground "white"))))
	  (font-lock-comment-face ((t (:italic t :foreground "#7C7C7C"))))
	  (font-lock-constant-face ((t (:foreground "#99CC99"))))
	  (font-lock-doc-string-face ((t (:foreground "A8FF60"))))
	  (font-lock-function-name-face ((t (:foreground "#FFB774"))))
	  (font-lock-keyword-face ((t (:foreground "#66B5FF"))))
	  (font-lock-preprocessor-face ((t (:foreground "#96CBFE"))))
	  (font-lock-reference-face ((t (:foreground "#99CC99"))))

	  (font-lock-regexp-grouping-backslash ((t (:foreground "#FF8000"))))
	  (font-lock-regexp-grouping-construct ((t (:foreground "red"))))

	  (font-lock-string-face ((t (:foreground "#A8FF60"))))
	  (font-lock-type-face ((t (:foreground "#FFB774"))))
	  (font-lock-variable-name-face ((t (:foreground "#C6C5FE"))))
	  (font-lock-warning-face ((t (:bold t :background "#FF6C60" :foreground "white"))))
	  (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
	  (region ((t (:background "#27292A"))))
	  (mode-line ((t (:background "grey75" :foreground "black"))))
	  (highlight ((t (:background "#111111"))))
	  (highline-face ((t (:background "SeaGreen"))))
	  (italic ((t (nil))))
	  (left-margin ((t (nil))))
	  (text-cursor ((t (:background "yellow" :foreground "black"))))
	  (toolbar ((t (nil))))
	  (underline ((nil (:underline nil))))
	  (zmacs-region ((t (:background "snow" :foreground "blue")))))))