;; MIT License Copyright (c) 2009 Burke Libbey <burke@burkelibbey.org>

(defun color-theme-ir-black ()
  (interactive)

  (let ((*normal*     "#F6F3E8")
        (*background* "#000000")
        (*string*     "#A8FF60")
        (*keyword*    "#66B5FF")
        (*method*     "#FFB774")
        (*comment*    "#7C7C7C")
        (*red*        "#FF6C60")
        (*operator*   "#FFFFFF") ; Does emacs have a face for this?
        (*class*      "#FFFFB6") ; again...
        (*variable*   "#C6C5FE"))

    (flet ((color (fgcolor &optional (bgcolor nil)) 
                  (cond ((null bgcolor)
                         `((t (:foreground ,fgcolor)))
                        ((null fgcolor)
                         `((t (:background ,bgcolor))))
                        (t
                         `((t (:foreground ,fgcolor :background ,bgcolor)))))))
           (face (face color &optional (bgcolor nil))
                 `(,(intern (concat "font-lock-" face "-face")) 
                   ,(color color bgcolor))))

      (color-theme-install
       `(color-theme-ir-black
         ((background-color . ,*background*)
          (background-mode . dark)
          (border-color . ,*background*)
          (cursor-color . "#A7A7A7")
          (foreground-color . "#F6F3E8")
          (mouse-color . "sienna1"))
         (default ,(color *normal* *background*))
         (blue ,(color "blue"))
         (bold ((t (:bold t))))
         (bold-italic ((t (:bold t))))
         (border-glyph ((t (nil))))
         (buffers-tab ,(color *normal* *background*))
        ,(face "builtin" *normal*)
        ,(face "comment" *comment*)
        ,(face "constant" "#99CC99")
        ,(face "doc-string" *string*)
        ,(face "function-name" *method*)
        ,(face "keyword" *keyword*)
        ,(face "preprocessor" *keyword*)
        ,(face "reference" "#99CC99")
        ,(face "regexp-grouping-backslash" "#FF8000")
        ,(face "regexp-grouping-construct" *red*)
        ,(face "string" *string*)
        ,(face "type" "#FFB774")
        ,(face "variable-name" *variable*)
         (font-lock-warning-face ,(color "white" "#FF6C60"))
         (gui-element ,(color *background* "#D4D0C8"))
         (region ,(color nil "#27292A"))
         (mode-line ,(color *background* "grey75"))
         (highlight ,(color nil "#111111"))
         (highline-face ,(color nil "SeaGreen"))
         (italic ((t (nil))))
         (left-margin ((t (nil))))
         (text-cursor ,(color *background* "yellow"))
         (toolbar ((t (nil))))
         (underline ((nil (:underline nil))))
         (zmacs-region ,(color "blue" "snow")))))))