;; MIT License Copyright (c) 2009 Burke Libbey <burke@burkelibbey.org>

(defun color-theme-ir-black ()
  (interactive)

  (let ((*normal*     "#F6F3E8")
        (*background* "#000000")
        (*string*     "#A8FF60")
        (*keyword*    "#66B5FF")
        (*comment*    "#7C7C7C")
        (*operator*   "#FFFFFF") ; Does emacs have a face for this?
        (*class*      "#FFFFB6") ; again...
        (*variable*   "#C6C5FE"))

    (flet ((fg-color (color) `((t (:foreground ,color))))
           (define-face (face color) 
             `(,(intern (concat "font-lock-" face "-face")) 
               ,(fg-color color))))

      (color-theme-install
       `(color-theme-ir-black
         ((background-color . ,*background*)
          (background-mode . dark)
          (border-color . ,*background*)
          (cursor-color . "#A7A7A7")
          (foreground-color . "#F6F3E8")
          (mouse-color . "sienna1"))
         (default ((t (:background ,*background* :foreground ,*normal*))))
         (blue ((t (:foreground "blue"))))
         (bold ((t (:bold t))))
         (bold-italic ((t (:bold t))))
         (border-glyph ((t (nil))))
         (buffers-tab ((t (:background ,*background* :foreground ,*normal*))))
        ,(define-face "builtin" *normal*)
        ,(define-face "comment" *comment*)
        ,(define-face "constant" "#99CC99")
        ,(define-face "doc-string" *string*)
        ,(define-face "function-name" "#FFB774")
        ,(define-face "keyword" *keyword*)
        ,(define-face "preprocessor" *keyword*)
        ,(define-face "reference" "#99CC99")
        ,(define-face "regexp-grouping-backslash" "#FF8000")
        ,(define-face "regexp-grouping-construct" "red")
        ,(define-face "string" *string*)
        ,(define-face "type" "#FFB774")
        ,(define-face "variable-name" *variable*)
         (font-lock-warning-face ((t (:bold t :background "#FF6C60" :foreground "white"))))
         (gui-element ((t (:background "#D4D0C8" :foreground ,*background*))))
         (region ((t (:background "#27292A"))))
         (mode-line ((t (:background "grey75" :foreground ,*background*))))
         (highlight ((t (:background "#111111"))))
         (highline-face ((t (:background "SeaGreen"))))
         (italic ((t (nil))))
         (left-margin ((t (nil))))
         (text-cursor ((t (:background "yellow" :foreground ,*background*))))
         (toolbar ((t (nil))))
         (underline ((nil (:underline nil))))
         (zmacs-region ((t (:background "snow" :foreground "blue")))))))))